name: post-review

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  post-review-test:
    if: github.event.repository.fork == false && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./md && ./md ./.github/config.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: flutter pub get
      - run: flutter test --no-pub