name: post-review
on:
  pull_request:
    types:
      - closed
    branches:
      - 'base'
env:
  FLUTTER_VERSION: '2.10.5'
  FLUTTER_CHANNEL: 'stable'
jobs:
  post-review-test:
    if: github.repository.isFork == false && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: $FLUTTER_CHANNEL
      - run: flutter pub get
      - run: flutter test --no-pub